# Generated by Django 5.0.6 on 2024-05-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='imagenes')),
            ],
        ),
    ]
