# Generated by Django 5.0.6 on 2024-05-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcial', '0002_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstadio', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
                ('descripcionEstadio', models.CharField(max_length=300)),
            ],
        ),
    ]
