# Generated by Django 5.0.6 on 2024-06-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcial', '0003_contenido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
