# Generated by Django 5.0.6 on 2024-06-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcial', '0004_delete_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenE3', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('tituloE3', models.CharField(max_length=200)),
                ('paisE3', models.CharField(max_length=200)),
                ('descripcionE3', models.CharField(max_length=300)),
            ],
        ),
    ]
